// src/web/assets/forms/src/js/components/NotificationPreview.vue
<template>
    <div class="fui-notification-preview">
        <div class="field field-wrapper flex">
            <div class="heading">
                <label class="">{{ t('formie', 'Email Preview') }}</label>

                <div class="instructions">
                    <p>{{ t('formie', 'The example below shows a preview of this email notification.') }}</p>
                </div>
            </div>

            <div class="">
                <a href="#" class="btn submit fui-refresh-btn" :class="{ 'fui-loading fui-loading-sm': loading }" @click.prevent="updatePreview">{{ t('formie', 'Refresh') }}</a>
            </div>
        </div>

        <div class="fui-email-preview">
            <div class="fui-email-header"></div>

            <div class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'To:') }}</div>
                <div class="fui-email-meta-value">{{ emailAddress(email.to) }}</div>
            </div>

            <div v-if="email.cc" class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'Cc:') }}</div>
                <div class="fui-email-meta-value">{{ emailAddress(email.cc) }}</div>
            </div>

            <div v-if="email.bcc" class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'Bcc:') }}</div>
                <div class="fui-email-meta-value">{{ emailAddress(email.bcc) }}</div>
            </div>

            <div class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'Subject:') }}</div>
                <div class="fui-email-meta-value">{{ email.subject }}</div>
            </div>

            <div v-if="email.replyTo" class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'Reply To:') }}</div>
                <div class="fui-email-meta-value">{{ emailAddress(email.replyTo) }}</div>
            </div>

            <div class="fui-email-meta">
                <div class="fui-email-meta-label">{{ t('formie', 'From:') }}</div>
                <div class="fui-email-meta-value">{{ emailAddress(email.from) }}</div>
            </div>

            <div class="fui-email-body">
                <!-- Note the odd use of length - we'll get an empty `<p>` back for empty -->
                <iframe
                    v-if="email.body && email.body.length > 10"
                    id="email-iframe"
                    src="about:blank"
                    frameborder="0"
                    style="height: 100vh; width: 100%;"
                ></iframe>

                <div v-else class="warning with-icon">{{ t('formie', 'No email content.') }}</div>
            </div>

            <div class="fui-email-footer"></div>

            <div v-if="loading" class="fui-loading-pane">
                <div class="fui-loading fui-loading-lg"></div>
            </div>

            <div v-if="error" class="fui-error-pane error">
                <div class="fui-error-content">
                    <span data-icon="alert"></span>

                    <span class="error" v-html="errorMessage"></span>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { mapState } from 'vuex';

export default {
    name: 'NotificationPreview',

    data() {
        return {
            email: {},
            error: false,
            errorMessage: '',
            loading: false,
        };
    },

    computed: {
        ...mapState({
            form: (state) => { return state.form; },
        }),

        notification() {
            // Not amazing, but provide/inject won't work
            return this.$parent.$parent.$parent.$parent.$parent.node._value;
        },

        isStencil() {
            return this.$store.state.form.isStencil;
        },
    },

    created() {
        this.updatePreview();
    },

    methods: {
        updateiFrame() {
            this.$nextTick().then(() => {
                const $iframe = this.$el.querySelector('#email-iframe');

                if ($iframe && this.email.body) {
                    const doc = $iframe.contentWindow.document;

                    if (doc) {
                        doc.open();
                        doc.write(`<html><head><title></title></head><body>${this.email.body}</body></html>`);
                        doc.close();
                    }
                }
            });
        },

        updatePreview() {
            this.error = false;
            this.errorMessage = '';
            this.loading = true;

            const data = {
                handle: this.form.handle,
                notification: this.notification,
            };

            // Only add the Form ID if not a stencil
            if (!this.isStencil) {
                data.formId = this.form.id;
            }

            Craft.sendActionRequest('POST', 'formie/email/preview', { data }).then((response) => {
                this.loading = false;

                if (response.data.error) {
                    this.error = true;

                    this.errorMessage = Craft.t('formie', 'An error occurred.');

                    if (response.data.error) {
                        this.errorMessage += `<br><br><code>${response.data.error}</code>`;
                    }

                    return;
                }

                this.email = response.data;

                this.updateiFrame();
            }).catch((error) => {
                this.loading = false;
                this.error = true;

                this.errorMessage = error;

                if (error.response.data.error) {
                    this.errorMessage += `<br><br><code>${error.response.data.error}</code>`;
                }
            });
        },

        emailAddress(object) {
            if (!object) {
                return '';
            }

            const [email] = Object.keys(object);

            if (object[email]) {
                return `${object[email]} <${email}>`;
            }

            return email;
        },
    },
};

</script>

<style lang="scss">

.fui-email-preview {
    position: relative;
    box-shadow: 0 0 0 1px rgba(49,49,93,.05), 0 2px 5px 0 rgba(49,49,93,.075), 0 1px 3px 0 rgba(49,49,93,.15);
    background-color: #fff;
    border-radius: 4px;
}

.fui-email-header,
.fui-email-footer {
    background: #f5f8fc;
    width: 100%;
    height: 20px;
}

.fui-email-header {
    border-bottom: 1px #e5e5e5 solid;
    border-radius: 4px 4px 0 0;
}

.fui-email-footer {
    border-top: 1px #e5e5e5 solid;
    border-radius: 0 0 4px 4px;
}

.fui-email-meta {
    display: flex;
    font-size: 13px;
    padding: 4px 0;
    border-bottom: 1px #e5e5e5 solid;
}

.fui-email-meta-label {
    width: 75px;
    text-align: right;
    font-weight: 700;
    color: #b2bac1;
    margin-right: 8px;
    flex: 0 0 auto;
}

.fui-email-body {
    min-height: 20rem;
    padding: 16px;
}

.fui-email-preview .fui-error-pane,
.fui-email-preview .fui-loading-pane {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: #fff;
    background: rgba(255, 255, 255, 0.7);
}

.fui-email-preview .fui-loading {
    position: absolute;
    top: 50%;
    left: 50%;
    background: #fff;
}

.fui-notification-preview .fui-refresh-btn {
    padding: 5px 10px;
    font-size: 12px;
    font-weight: 600;
    height: auto;
}

.fui-notification-preview .field {
    justify-content: space-between;
}

.fui-email-preview .fui-error-pane {
    align-items: center;
    justify-content: center;
    display: flex;

    [data-icon] {
        display: block;
        font-size: 3em;
        margin-bottom: 0.5rem;
    }
}

.fui-email-preview .fui-error-content {
    text-align: center;
    max-width: 35rem;
}

</style>

// src/web/assets/cp/src/form-builder/components/NotificationPreview.jsx
import { useState, useEffect, useRef } from 'react';
import { cn } from '@verbb/plugin-kit-react/utils';
import { useTranslation } from '@verbb/plugin-kit-react/hooks';
import { Button, Icon } from '@verbb/plugin-kit-react/components';
import { FieldLayout, useSchemaEngineContext } from '@verbb/plugin-kit-react/forms';
import { ErrorState } from '@verbb/plugin-kit-react/utils';
import { useFormValues } from '@form-builder/hooks/useFormTools';
import { takeAtLeast } from '@verbb/plugin-kit-core';

function NotificationPreview() {
    const form = useSchemaEngineContext();
    const formValues = useFormValues();
    const [email, setEmail] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);
    const iframeRef = useRef(null);

    const t = useTranslation();

    useEffect(() => {
        updatePreview();
    }, []);

    const updateiFrame = () => {
        if (iframeRef.current && email?.body) {
            const doc = iframeRef.current.contentWindow.document;

            if (doc) {
                doc.open();
                doc.write(`<html><head><title></title></head><body>${email.body}</body></html>`);
                doc.close();
            }
        }
    };

    useEffect(() => {
        if (email) {
            updateiFrame();
        }
    }, [email]);

    const updatePreview = async() => {
        setError(null);
        setLoading(true);

        const data = {
            formId: formValues?.id,
            handle: formValues?.handle,
            isStencil: formValues?.isStencil,
            notification: form?.store?.state?.values ?? {},
        };

        try {
            const response = await takeAtLeast(500)(
                Craft.sendActionRequest('POST', 'formie/email/preview', { data }),
            );

            if (response.data.error) {
                throw response.data.error;
            }

            setEmail(response.data);
        } catch (error) {
            setError(error);
        }

        setLoading(false);
    };

    const emailAddress = (object) => {
        if (!object) {
            return '';
        }

        const [email] = Object.keys(object);

        if (object[email]) {
            return `${object[email]} <${email}>`;
        }

        return email;
    };

    return (
        <FieldLayout
            name="emailPreview"
            label={t('Email Preview')}
            instructions={t('The example below shows a preview of this email notification.')}
            headerEnd={(
                <Button
                    variant="primary"
                    type="button"
                    onClick={updatePreview}
                    loading={loading}
                >
                    {t('Refresh')}
                </Button>
            )}
        >
            <div className={cn(
                'relative bg-white rounded',
                'shadow-[0_0_0_1px_rgba(49,49,93,0.05),0_2px_5px_0_rgba(49,49,93,0.075),0_1px_3px_0_rgba(49,49,93,0.15)]',
            )}>
                <div className={cn(
                    'w-full h-5 bg-[#f5f8fc]',
                    'border-b border-[#e5e5e5] border-solid',
                    'rounded-t',
                )}></div>

                <div className={cn(
                    'flex text-[13px] py-1',
                    'border-b border-[#e5e5e5] border-solid',
                )}>
                    <div className={cn(
                        'w-[75px] text-right font-bold text-[#60758a]',
                        'mr-2 flex-none',
                    )}>{t('To:')}</div>
                    <div>{emailAddress(email?.to)}</div>
                </div>

                {email?.cc && (
                    <div className={cn(
                        'flex text-[13px] py-1',
                        'border-b border-[#e5e5e5] border-solid',
                    )}>
                        <div className={cn(
                            'w-[75px] text-right font-bold text-[#60758a]',
                            'mr-2 flex-none',
                        )}>{t('Cc:')}</div>
                        <div>{emailAddress(email.cc)}</div>
                    </div>
                )}

                {email?.bcc && (
                    <div className={cn(
                        'flex text-[13px] py-1',
                        'border-b border-[#e5e5e5] border-solid',
                    )}>
                        <div className={cn(
                            'w-[75px] text-right font-bold text-[#60758a]',
                            'mr-2 flex-none',
                        )}>{t('Bcc:')}</div>
                        <div>{emailAddress(email.bcc)}</div>
                    </div>
                )}

                <div className={cn(
                    'flex text-[13px] py-1',
                    'border-b border-[#e5e5e5] border-solid',
                )}>
                    <div className={cn(
                        'w-[75px] text-right font-bold text-[#60758a]',
                        'mr-2 flex-none',
                    )}>{t('Subject:')}</div>
                    <div>{email?.subject}</div>
                </div>

                {email?.replyTo && (
                    <div className={cn(
                        'flex text-[13px] py-1',
                        'border-b border-[#e5e5e5] border-solid',
                    )}>
                        <div className={cn(
                            'w-[75px] text-right font-bold text-[#60758a]',
                            'mr-2 flex-none',
                        )}>{t('Reply To:')}</div>
                        <div>{emailAddress(email.replyTo)}</div>
                    </div>
                )}

                <div className={cn(
                    'flex text-[13px] py-1',
                    'border-b border-[#e5e5e5] border-solid',
                )}>
                    <div className={cn(
                        'w-[75px] text-right font-bold text-[#60758a]',
                        'mr-2 flex-none',
                    )}>{t('From:')}</div>
                    <div>{emailAddress(email?.from)}</div>
                </div>

                <div className={cn(
                    'min-h-[20rem] p-4',
                )}>
                    {email?.body && email.body.length ? (
                        <iframe
                            ref={iframeRef}
                            src="about:blank"
                            sandbox="allow-same-origin"
                            frameBorder="0"
                            style={{ height: '100vh', width: '100%' }}
                        />
                    ) : (
                        <span className="flex items-center gap-1 text-warning">
                            <Icon icon="triangle-exclamation" className="block size-4 shrink-0" />
                            <span className="flex-1">{email?.warning || t('No email content.')}</span>
                        </span>
                    )}
                </div>

                <div className={cn(
                    'w-full h-5 bg-[#f5f8fc]',
                    'border-t border-[#e5e5e5] border-solid',
                    'rounded-b',
                )}></div>

                {loading && (
                    <div className={cn(
                        'absolute w-full h-full top-0 left-0',
                        'bg-white/70',
                    )}>
                        <div className={cn(
                            'absolute top-1/2 left-1/2 bg-white',
                        )}></div>
                    </div>
                )}

                {error && (
                    <div className={cn(
                        'absolute w-full h-full top-0 left-0',
                        'bg-white/70',
                        'flex items-center justify-center',
                    )}>
                        <ErrorState
                            error={error}
                            size="sm"
                            message={t('Unable to generate email preview.')}
                            detailsLabel={t('Show error details')}
                            actionLabel={t('Try Again')}
                            onAction={updatePreview}
                            className="w-full h-full"
                        />
                    </div>
                )}
            </div>
        </FieldLayout>
    );
}

export { NotificationPreview };
