// src/web/assets/cp/src/form-builder/components/preview/ElementFieldPreview.jsx
import React, { useMemo } from 'react';

const getFieldValue = (field, key, fallback = undefined) => {
    if (!field || typeof field !== 'object') {
        return fallback;
    }

    if (field[key] !== undefined) {
        return field[key];
    }

    if (field.settings && field.settings[key] !== undefined) {
        return field.settings[key];
    }

    return fallback;
};

const getDefaultValueOption = (field) => {
    const options = getFieldValue(field, 'defaultValueOptions', []);

    if (Array.isArray(options) && options.length && options[0]) {
        return options[0];
    }

    return {};
};

const toSelectedValues = (defaultValue) => {
    if (Array.isArray(defaultValue)) {
        return defaultValue.map((value) => {
            if (value && typeof value === 'object' && 'value' in value) {
                return String(value.value);
            }

            return String(value);
        });
    }

    if (defaultValue && typeof defaultValue === 'object' && 'value' in defaultValue) {
        return [String(defaultValue.value)];
    }

    if (defaultValue === null || defaultValue === undefined || defaultValue === '') {
        return [];
    }

    return [String(defaultValue)];
};

const FALLBACK_PREVIEW_OPTIONS = [
    { label: 'Example One', value: 'one' },
    { label: 'Example Two', value: 'two' },
    { label: 'Example Three', value: 'three' },
];
const MAX_VISIBLE_OPTIONS = 5;

const normalizeOptions = (fieldOptions) => {
    if (!Array.isArray(fieldOptions) || !fieldOptions.length) {
        return FALLBACK_PREVIEW_OPTIONS;
    }

    return fieldOptions.map((option, index) => {
        const value = option?.value ?? `option-${index + 1}`;
        const label = option?.label ?? String(value);

        return {
            label,
            value: String(value),
        };
    });
};

const FormieElementFieldPreview = ({ field }) => {
    const displayType = getFieldValue(field, 'displayType', 'dropdown');
    const layout = getFieldValue(field, 'layout', 'vertical');
    const layoutClassName = `formie-field-preview-layout-${layout || 'vertical'}`;
    const isMulti = Boolean(getFieldValue(field, 'multi', false));
    const placeholder = getFieldValue(field, 'placeholder', '');
    const defaultValue = getFieldValue(field, 'defaultValue', null);
    const defaultValueOption = getDefaultValueOption(field);
    const selectedValues = useMemo(() => {
        return toSelectedValues(defaultValue);
    }, [defaultValue]);
    const options = useMemo(() => {
        const fieldOptions = getFieldValue(field, 'options', null);
        return normalizeOptions(fieldOptions);
    }, [field]);
    const visibleOptions = options.slice(0, MAX_VISIBLE_OPTIONS);
    const hiddenCount = Math.max(options.length - visibleOptions.length, 0);

    if (displayType === 'dropdown') {
        return (
            <select
                className="formie-field-preview-select"
                multiple={isMulti}
                value={isMulti ? selectedValues : (selectedValues[0] || '')}
                onChange={() => {}}
                disabled
            >
                <option value="">{defaultValueOption.label || placeholder || ''}</option>

                {options.map((option, index) => {
                    return (
                        <option key={index} value={String(option.value)}>
                            {option.label}
                        </option>
                    );
                })}
            </select>
        );
    }

    if (displayType === 'checkboxes') {
        return (
            <div className={`formie-field-preview-checkboxes ${layoutClassName}`}>
                {visibleOptions.map((option, index) => {
                    return (
                        <div key={index} className="formie-field-preview-checkbox">
                            <input
                                type="checkbox"
                                value={option.value}
                                checked={selectedValues.includes(String(option.value))}
                                readOnly
                            />
                            <label>{option.label}</label>
                        </div>
                    );
                })}

                {hiddenCount > 0 && (
                    <div className="formie-field-preview-instructions">
                        ... {hiddenCount} {Craft.t('formie', 'more')}
                    </div>
                )}
            </div>
        );
    }

    if (displayType === 'radio') {
        return (
            <div className={`formie-field-preview-radios ${layoutClassName}`}>
                {visibleOptions.map((option, index) => {
                    return (
                        <div key={index} className="formie-field-preview-radio">
                            <input
                                type="radio"
                                value={option.value}
                                checked={selectedValues.includes(String(option.value))}
                                readOnly
                            />
                            <label>{option.label}</label>
                        </div>
                    );
                })}

                {hiddenCount > 0 && (
                    <div className="formie-field-preview-instructions">
                        ... {hiddenCount} {Craft.t('formie', 'more')}
                    </div>
                )}
            </div>
        );
    }

    return null;
};

export { FormieElementFieldPreview };

// src/web/assets/forms/src/js/components/ElementFieldPreview.vue
<template>
    <div>
        <div v-if="field.settings.displayType == 'dropdown'">
            <select class="fui-field-select" :multiple="field.settings.multi">
                <option value="">{{ defaultValue.label || field.settings.placeholder }}</option>

                <option v-for="(option, index) in options" :key="index" :selected="defaultValue.value === option.value ? true : false">
                    {{ option.label }}
                </option>
            </select>
        </div>

        <div v-if="field.settings.displayType == 'checkboxes'">
            <div v-for="(option, index) in options" :key="index" class="fui-field-checkbox">
                <input :value="option.value" type="checkbox" :checked="defaultValue.value === option.value ? true : false">
                <label>{{ option.label }}</label>
            </div>

            <div v-if="total > options.length" class="fui-field-instructions">... {{ total - options.length }} {{ t('formie', 'more') }}</div>
        </div>

        <div v-if="field.settings.displayType == 'radio'">
            <div v-for="(option, index) in options" :key="index" class="fui-field-radio">
                <input :value="option.value" type="radio" :checked="defaultValue.value === option.value ? true : false">
                <label>{{ option.label }}</label>
            </div>

            <div v-if="total > options.length" class="fui-field-instructions">... {{ total - options.length }} {{ t('formie', 'more') }}</div>
        </div>
    </div>
</template>

<script>

import { debounce } from 'lodash-es';

export default {
    name: 'ElementFieldPreview',

    props: {
        field: {
            type: Object,
            required: true,
        },
    },

    data() {
        return {
            total: null,
            options: [],
        };
    },

    computed: {
        sources() {
            return this.field.settings.sources;
        },

        source() {
            return this.field.settings.source;
        },

        displayType() {
            return this.field.settings.displayType;
        },

        defaultValue() {
            if (this.field.defaultValueOptions) {
                if (this.field.defaultValueOptions.length && this.field.defaultValueOptions[0]) {
                    return this.field.defaultValueOptions[0];
                }
            }

            return {};
        },
    },

    watch: {
        // Wait for the user to pick a few checkboxes for sources
        sources: debounce(function(newValue) {
            this.updateSources();
        }, 2000),

        source: debounce(function(newValue) {
            this.updateSources();
        }, 2000),

        displayType(newValue) {
            this.updateSources();
        },
    },

    created() {
        // If no elements fetch them. Likely when cloning an existing field, but because we don't
        // store the elements in field settings, we have to re-fetch them on-demand.
        if (this.field.elements) {
            this.options = this.field.elements.options || [];
            this.total = this.field.elements.total;
        } else {
            this.updateSources();
        }
    },

    methods: {
        updateSources() {
            if (this.field.settings.displayType === 'dropdown') {
                return;
            }

            const data = { field: this.field };

            Craft.sendActionRequest('POST', 'formie/fields/get-element-select-options', { data }).then((response) => {
                this.options = response.data.options || [];
                this.total = response.data.total;
            });
        },
    },
};

</script>
