// src/web/assets/cp/src/form-builder/components/NotificationTest.jsx
import { useState, useEffect } from 'react';
import { cn } from '@verbb/plugin-kit-react/utils';
import { useTranslation } from '@verbb/plugin-kit-react/hooks';
import { Alert, Button, Input } from '@verbb/plugin-kit-react/components';
import { FieldLayout, useSchemaEngineContext } from '@verbb/plugin-kit-react/forms';
import { useFormValues } from '@form-builder/hooks/useFormTools';
import { takeAtLeast, getErrorMessage } from '@verbb/plugin-kit-core';

function NotificationTest({ userEmail }) {
    const form = useSchemaEngineContext();
    const formValues = useFormValues();
    const [to, setTo] = useState('');
    const [error, setError] = useState(null);
    const [success, setSuccess] = useState(false);
    const [loading, setLoading] = useState(false);
    const [successMessage, setSuccessMessage] = useState('');

    const t = useTranslation();

    // Populate the current email on mount
    useEffect(() => {
        if (userEmail) {
            setTo(userEmail);
        }
    }, [userEmail]);

    const sendTestEmail = async() => {
        setError(null);
        setSuccess(false);
        setLoading(true);
        setSuccessMessage('');

        const data = {
            formId: formValues?.id,
            handle: formValues?.handle,
            isStencil: formValues?.isStencil,
            notification: form?.store?.state?.values ?? {},
            to,
        };

        try {
            const response = await takeAtLeast(500)(
                Craft.sendActionRequest('POST', 'formie/email/send-test-email', { data }),
            );

            if (response.data.success) {
                setSuccess(true);
                setSuccessMessage(t('Email sent successfully. Please check your email.'));
            }

            if (response.data.error) {
                throw response.data.error;
            }
        } catch (error) {
            setError(getErrorMessage(error));
        }

        setLoading(false);
    };

    return (
        <FieldLayout
            name="to"
            label={t('Send Test Email')}
            instructions={t('Use the form below to send a test email to the nominated email address.')}
        >
            <div className={cn('flex items-center gap-4')}>
                <Input
                    id="to"
                    value={to}
                    onChange={(e) => { return setTo(e.target.value); }}
                    type="text"
                    placeholder="Enter email address"
                />

                <Button
                    variant="primary"
                    onClick={sendTestEmail}
                    loading={loading}
                >
                    {t('Send Test Email')}
                </Button>
            </div>

            {error && (
                <Alert
                    variant="error"
                    size="sm"
                    heading={error.heading}
                    announce="assertive"
                    detailsLabel={t('Show error details')}
                    copyLabel={t('Copy error details')}
                    copyable={Boolean(error.traceAsArray?.length)}
                    className="mt-2.5"
                >
                    {error.text}
                    {error.traceAsArray?.length ? <pre slot="details">{error.traceAsArray.join('\n\n')}</pre> : null}
                </Alert>
            )}

            {success && (
                <Alert variant="success" size="sm" announce="polite" className="mt-2.5">
                    {successMessage}
                </Alert>
            )}
        </FieldLayout>
    );
}

export { NotificationTest };

// src/web/assets/forms/src/js/components/NotificationTest.vue
<template>
    <div class="fui-notification-test">
        <div class="field field-wrapper">
            <div class="heading">
                <label class="">{{ t('formie', 'Send Test Email') }}</label>

                <div class="instructions">
                    <p>{{ t('formie', 'Use the form below to send a test email to the nominated email address.') }}</p>
                </div>
            </div>

            <div class="fui-test-input">
                <input v-model="to" class="text fullwidth" type="text">

                <a href="#" class="btn submit fui-refresh-btn" :class="{ 'fui-loading fui-loading-sm': loading }" @click.prevent="sendTestEmail">{{ t('formie', 'Send Test Email') }}</a>
            </div>
        </div>

        <div v-if="error || success" class="fui-message-pane" :class="{ 'error': error, 'success': success }">
            <div class="fui-message-content">
                <span v-if="error" data-icon="alert"></span>

                <span v-html="message"></span>
            </div>
        </div>
    </div>
</template>

<script>
import { mapState } from 'vuex';

export default {
    name: 'NotificationTest',

    data() {
        return {
            to: null,
            error: false,
            success: false,
            loading: false,
            message: '',
        };
    },

    computed: {
        ...mapState({
            form: (state) => { return state.form; },
        }),

        isStencil() {
            return this.$store.state.form.isStencil;
        },

        notification() {
            // Not amazing, but provide/inject won't work
            return this.$parent.$parent.$parent.$parent.$parent.node._value;
        },
    },

    created() {
        // Populate the current email
        if (this.$attrs.userEmail) {
            this.to = this.$attrs.userEmail;
        }
    },

    methods: {
        sendTestEmail() {
            this.error = false;
            this.success = false;
            this.loading = true;
            this.message = '';

            const data = {
                handle: this.form.handle,
                notification: this.notification,
                to: this.to,
            };

            if (!this.isStencil) {
                data.formId = this.form.id;
            }

            Craft.sendActionRequest('POST', 'formie/email/send-test-email', { data }).then((response) => {
                this.loading = false;

                if (response.data.success) {
                    this.success = true;

                    this.message = Craft.t('formie', 'Email sent successfully. Please check your email.');
                }

                if (response.data.error) {
                    this.error = true;

                    this.message = Craft.t('formie', 'Error sending test email.');

                    if (response.data.error) {
                        this.message += `<br><br><code>${response.data.error}</code>`;
                    }


                }
            }).catch((error) => {
                this.loading = false;
                this.error = true;

                this.message = error;

                if (error.response.data.error) {
                    this.message += `<br><br><code>${error.response.data.error}</code>`;
                }
            });
        },
    },
};

</script>

<style lang="scss">

.fui-test-input {
    display: flex;

    .text {
        margin-right: 1rem;
    }
}

.fui-notification-test .fui-message-pane {
    margin-top: 10px;
}

</style>
